swagger: "2.0"
info:
  title: Petstore API
  version: 1.0.0
  description: A sample API for testing Cherrybomb security testing tool

host: localhost:8080
basePath: /v1
schemes:
  - http

paths:
  /pets:
    get:
      summary: List all pets
      security:
        - apiKey: []
      responses:
        200:
          description: A list of pets
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
        401:
          description: Unauthorized
    post:
      summary: Create a pet
      security:
        - apiKey: []
      parameters:
        - in: body
          name: pet
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        201:
          description: Pet created successfully
        401:
          description: Unauthorized

definitions:
  Pet:
    type: object
    required:
      - name
      - type
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      type:
        type: string
        enum:
          - dog
          - cat
          - bird
      status:
        type: string
        enum:
          - available
          - pending
          - sold

securityDefinitions:
  apiKey:
    type: apiKey
    name: X-API-Key
    in: header
