openapi: "3.0.0"
info:
  title: Petstore API
  version: 1.0.0
  description: A sample API for testing Casper security testing tool

servers:
  - url: http://localhost:8080/v1
    description: Local development server

paths:
  /pets:
    get:
      summary: List all pets
      security:
        - apiKey: []
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '401':
          description: Unauthorized
    post:
      summary: Create a pet
      security:
        - apiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Pet created successfully
        '401':
          description: Unauthorized

components:
  schemas:
    Pet:
      type: object
      required:
        - name
        - type
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        type:
          type: string
          enum:
            - dog
            - cat
            - bird
        status:
          type: string
          enum:
            - available
            - pending
            - sold
  
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header
